<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FamilyMemberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Kosongkan tabel terlebih dahulu sebelum diisi agar tidak duplikat jika dijalankan ulang
        DB::table('family_members')->truncate();

        $data = [
            ['id' => 1, 'name' => 'Mas Moenandar', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '2, 3', 'is_alive' => 0, 'biografi' => 'Leluhur Utama. Menduda lalu menikah lagi.'],
            ['id' => 2, 'name' => 'Mbah Istri Pertama', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '1', 'is_alive' => 0, 'biografi' => 'Istri Ke-1. Meninggal saat anak masih kecil.'],
            ['id' => 3, 'name' => 'Mas Ajeng Amini', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '1', 'is_alive' => 0, 'biografi' => 'Istri Ke-2 Mbah Moenandar.'],
            ['id' => 4, 'name' => 'Mas Kartono', 'gender' => 'M', 'father_id' => 1, 'mother_id' => 2, 'spouse_id' => null, 'is_alive' => 0, 'biografi' => 'Anak Istri 1 (Meninggal Balita)'],
            ['id' => 5, 'name' => 'Mas Kahirman', 'gender' => 'M', 'father_id' => 1, 'mother_id' => 2, 'spouse_id' => '222, 225, 233', 'is_alive' => 0, 'biografi' => 'Anak Istri 1'],
            ['id' => 6, 'name' => 'Mas Ajeng Murtiwi', 'gender' => 'F', 'father_id' => 1, 'mother_id' => 3, 'spouse_id' => '18', 'is_alive' => 0, 'biografi' => 'Anak Istri 2 (Anak ke-1)'],
            ['id' => 7, 'name' => 'Mas Ajeng Kusilah', 'gender' => 'F', 'father_id' => 1, 'mother_id' => 3, 'spouse_id' => '19', 'is_alive' => 0, 'biografi' => 'Anak Istri 2 (Anak ke-2)'],
            ['id' => 8, 'name' => 'Mas Ayu Usiati', 'gender' => 'F', 'father_id' => 1, 'mother_id' => 3, 'spouse_id' => null, 'is_alive' => 0, 'biografi' => 'Anak Istri 2 (Meninggal Balita)'],
            ['id' => 9, 'name' => 'Mas Ajeng Mintarsih', 'gender' => 'F', 'father_id' => 1, 'mother_id' => 3, 'spouse_id' => '20', 'is_alive' => 0, 'biografi' => 'Anak Istri 2 (Anak ke-4)'],
            ['id' => 10, 'name' => 'Mas Ayu Herdiyah', 'gender' => 'F', 'father_id' => 1, 'mother_id' => 3, 'spouse_id' => '117', 'is_alive' => 1, 'biografi' => 'Anak Istri 2 (Anak ke-5)'],
            ['id' => 11, 'name' => 'Mas Ayu Umiyati', 'gender' => 'F', 'father_id' => 1, 'mother_id' => 3, 'spouse_id' => null, 'is_alive' => 0, 'biografi' => 'Anak Istri 2 (Meninggal Balita)'],
            ['id' => 12, 'name' => 'Mas Mochamad Ilyas', 'gender' => 'M', 'father_id' => 1, 'mother_id' => 3, 'spouse_id' => '21', 'is_alive' => 1, 'biografi' => 'Anak Istri 2 (Anak ke-7)'],
            ['id' => 13, 'name' => 'Mas Muhadi', 'gender' => 'M', 'father_id' => 1, 'mother_id' => 3, 'spouse_id' => '22', 'is_alive' => 1, 'biografi' => 'Anak Istri 2 (Anak ke-8 / Pakde Hadi)'],
            ['id' => 14, 'name' => 'Mas Hardono', 'gender' => 'M', 'father_id' => 1, 'mother_id' => 3, 'spouse_id' => '23', 'is_alive' => 1, 'biografi' => 'Anak Istri 2 (Anak ke-9 / Pakde Don)'],
            ['id' => 15, 'name' => 'Mas Nursaid', 'gender' => 'M', 'father_id' => 1, 'mother_id' => 3, 'spouse_id' => '187', 'is_alive' => 0, 'biografi' => 'Anak Istri 2 (Anak ke-10 / Pakde Nanung)'],
            ['id' => 16, 'name' => 'Mas Nugroho', 'gender' => 'M', 'father_id' => 1, 'mother_id' => 3, 'spouse_id' => '24', 'is_alive' => 1, 'biografi' => 'Anak Istri 2 (Anak ke-11 / Papah Hoho)'],
            ['id' => 17, 'name' => 'Mas Ajeng Murniati', 'gender' => 'F', 'father_id' => 1, 'mother_id' => 3, 'spouse_id' => '25', 'is_alive' => 1, 'biografi' => 'Anak Istri 2 (Anak ke-12)'],
            ['id' => 18, 'name' => 'Pakde Haryomo', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '6', 'is_alive' => 0, 'biografi' => 'Suami Bude Murtiwi'],
            ['id' => 19, 'name' => 'Pakde Widjanarko', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '7', 'is_alive' => 0, 'biografi' => 'Suami Bude Kusilah'],
            ['id' => 20, 'name' => 'Pakde Sumadi (Soemadi Sastra Atmadja)', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '9', 'is_alive' => 0, 'biografi' => 'Suami Bude Mintarsih'],
            ['id' => 21, 'name' => 'Sustiyastuti', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '12', 'is_alive' => 1, 'biografi' => 'Istri Pakde Ilyas'],
            ['id' => 22, 'name' => 'Tien', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '13', 'is_alive' => 0, 'biografi' => 'Istri Pakde Muhadi'],
            ['id' => 23, 'name' => 'Kusmawati', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '14', 'is_alive' => 1, 'biografi' => 'Istri Pakde Hardono'],
            ['id' => 24, 'name' => 'Sulistyanti', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '16', 'is_alive' => 1, 'biografi' => 'Istri Papah Hoho'],
            ['id' => 25, 'name' => 'Hendro Mugiyono', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '17', 'is_alive' => 1, 'biografi' => 'Suami Bude Murniati'],
            ['id' => 26, 'name' => 'H.R. Bambang Djatmiko, ST, MM', 'gender' => 'M', 'father_id' => 18, 'mother_id' => 6, 'spouse_id' => '27', 'is_alive' => 0, 'biografi' => 'Anak Bude Murtiwi'],
            ['id' => 27, 'name' => 'Hj. Dwi Indiarti', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '26', 'is_alive' => 1, 'biografi' => 'Istri H.R. Bambang'],
            ['id' => 28, 'name' => 'Nursiati (Mbak Titik)', 'gender' => 'F', 'father_id' => 18, 'mother_id' => 6, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Bude Murtiwi'],
            ['id' => 29, 'name' => 'Edy Putranto', 'gender' => 'M', 'father_id' => 18, 'mother_id' => 6, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Bude Murtiwi'],
            ['id' => 30, 'name' => 'Retno Wijayanti (Mbak Mencus)', 'gender' => 'F', 'father_id' => 18, 'mother_id' => 6, 'spouse_id' => '31', 'is_alive' => 0, 'biografi' => 'Anak Bude Murtiwi'],
            ['id' => 31, 'name' => 'Adhy Hertanto', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '30', 'is_alive' => 0, 'biografi' => 'Suami Retno Wijayanti'],
            ['id' => 32, 'name' => 'Mas Sony', 'gender' => 'M', 'father_id' => 18, 'mother_id' => 6, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Bude Murtiwi'],
            ['id' => 33, 'name' => 'Mbak Tipluk', 'gender' => 'F', 'father_id' => 18, 'mother_id' => 6, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Bude Murtiwi'],
            ['id' => 34, 'name' => 'Mas Lilik', 'gender' => 'M', 'father_id' => 18, 'mother_id' => 6, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Bude Murtiwi'],
            ['id' => 35, 'name' => 'Ina', 'gender' => 'F', 'father_id' => 18, 'mother_id' => 6, 'spouse_id' => '36', 'is_alive' => 1, 'biografi' => 'Anak Bude Murtiwi'],
            ['id' => 36, 'name' => 'Cacak', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '35', 'is_alive' => 1, 'biografi' => 'Suami Ina'],
            ['id' => 37, 'name' => 'Ani Murtiani', 'gender' => 'F', 'father_id' => 18, 'mother_id' => 6, 'spouse_id' => '38', 'is_alive' => 1, 'biografi' => 'Anak Bude Murtiwi'],
            ['id' => 38, 'name' => 'H. Achmad Rifai', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '37', 'is_alive' => 1, 'biografi' => 'Suami Ani Murtiani'],
            ['id' => 39, 'name' => 'Rr. Rieke Puspa Wardhani, SH', 'gender' => 'F', 'father_id' => 26, 'mother_id' => 27, 'spouse_id' => '40', 'is_alive' => 0, 'biografi' => 'Anak Bambang Djatmiko'],
            ['id' => 40, 'name' => 'Gunawan Wibisono, SH', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '39', 'is_alive' => 1, 'biografi' => 'Suami Rr. Rieke'],
            ['id' => 41, 'name' => 'Diwan Pramana Wibisono', 'gender' => 'M', 'father_id' => 40, 'mother_id' => 39, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bambang Djatmiko'],
            ['id' => 42, 'name' => 'Dimar Prawira Wibisono', 'gender' => 'M', 'father_id' => 40, 'mother_id' => 39, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bambang Djatmiko'],
            ['id' => 43, 'name' => 'R. Dandy Kusma Wardhana, SE', 'gender' => 'M', 'father_id' => 26, 'mother_id' => 27, 'spouse_id' => '44', 'is_alive' => 1, 'biografi' => 'Anak Bambang Djatmiko'],
            ['id' => 44, 'name' => 'Feni Arista Hartini, SH', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '43', 'is_alive' => 1, 'biografi' => 'Istri R. Dandy'],
            ['id' => 45, 'name' => 'R. Devandra Azka Wardhana', 'gender' => 'M', 'father_id' => 43, 'mother_id' => 44, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bambang Djatmiko'],
            ['id' => 46, 'name' => 'R. Keenandra Adinata Wardhana', 'gender' => 'M', 'father_id' => 43, 'mother_id' => 44, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bambang Djatmiko'],
            ['id' => 47, 'name' => 'Aria Raditya', 'gender' => 'M', 'father_id' => 31, 'mother_id' => 30, 'spouse_id' => '48', 'is_alive' => 1, 'biografi' => 'Anak Retno Wijayanti'],
            ['id' => 48, 'name' => 'Duwi Wijayanti', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '47', 'is_alive' => 1, 'biografi' => 'Istri Aria Raditya'],
            ['id' => 49, 'name' => 'Inara Ariandra Alfatih', 'gender' => 'F', 'father_id' => 47, 'mother_id' => 48, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Retno Wijayanti'],
            ['id' => 50, 'name' => 'Aryani Ditha Puspita', 'gender' => 'F', 'father_id' => 31, 'mother_id' => 30, 'spouse_id' => '51', 'is_alive' => 1, 'biografi' => 'Anak Retno Wijayanti'],
            ['id' => 51, 'name' => 'Kristoper Derang', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '50', 'is_alive' => 1, 'biografi' => 'Suami Aryani Ditha'],
            ['id' => 52, 'name' => 'Muhammad Athafariz Derang', 'gender' => 'M', 'father_id' => 51, 'mother_id' => 50, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Retno Wijayanti'],
            ['id' => 53, 'name' => 'Ariyani Devie Afria', 'gender' => 'F', 'father_id' => 31, 'mother_id' => 30, 'spouse_id' => '54', 'is_alive' => 1, 'biografi' => 'Anak Retno Wijayanti'],
            ['id' => 54, 'name' => 'Fitriyanto', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '53', 'is_alive' => 1, 'biografi' => 'Suami Ariyani Devie'],
            ['id' => 55, 'name' => 'Arief Wisaksono', 'gender' => 'M', 'father_id' => 32, 'mother_id' => null, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Mas Sony'],
            ['id' => 56, 'name' => 'Ariyanti Ika Nurindahsih', 'gender' => 'F', 'father_id' => 32, 'mother_id' => null, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Mas Sony'],
            ['id' => 57, 'name' => 'Wildhan Adrianto', 'gender' => 'M', 'father_id' => 32, 'mother_id' => null, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Mas Sony'],
            ['id' => 58, 'name' => 'Hamied Endrianto', 'gender' => 'M', 'father_id' => 32, 'mother_id' => null, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Mas Sony'],
            ['id' => 59, 'name' => 'Bagus Satrio Wibowo', 'gender' => 'M', 'father_id' => 38, 'mother_id' => 37, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Ani Murtiani'],
            ['id' => 60, 'name' => 'Arsinta Kirana Nisa', 'gender' => 'F', 'father_id' => 38, 'mother_id' => 37, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Ani Murtiani'],
            ['id' => 61, 'name' => 'Totok Kudarminto', 'gender' => 'M', 'father_id' => 19, 'mother_id' => 7, 'spouse_id' => '65', 'is_alive' => 1, 'biografi' => 'Anak Bude Kusilah'],
            ['id' => 62, 'name' => 'Kunwindrati', 'gender' => 'F', 'father_id' => 19, 'mother_id' => 7, 'spouse_id' => '74', 'is_alive' => 1, 'biografi' => 'Anak Bude Kusilah'],
            ['id' => 63, 'name' => 'Kusbardini', 'gender' => 'F', 'father_id' => 19, 'mother_id' => 7, 'spouse_id' => '83', 'is_alive' => 1, 'biografi' => 'Anak Bude Kusilah'],
            ['id' => 64, 'name' => 'Kusmahadi', 'gender' => 'M', 'father_id' => 19, 'mother_id' => 7, 'spouse_id' => '90', 'is_alive' => 1, 'biografi' => 'Anak Bude Kusilah'],
            ['id' => 65, 'name' => 'Etty Dyah Triwahyuwati', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '61', 'is_alive' => 1, 'biografi' => 'Istri Totok Kudarminto'],
            ['id' => 66, 'name' => 'Ika Tauricia', 'gender' => 'F', 'father_id' => 61, 'mother_id' => 65, 'spouse_id' => '67', 'is_alive' => 1, 'biografi' => 'Cucu Bude Kusilah'],
            ['id' => 67, 'name' => 'Muchamad Sumawan', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '66', 'is_alive' => 1, 'biografi' => 'Suami Ika Tauricia'],
            ['id' => 68, 'name' => 'Nikeisha Anindya', 'gender' => 'F', 'father_id' => 67, 'mother_id' => 66, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cicit Bude Kusilah'],
            ['id' => 69, 'name' => 'Nidya Evawardhani', 'gender' => 'F', 'father_id' => 61, 'mother_id' => 65, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Kusilah'],
            ['id' => 70, 'name' => 'Febry Triawan', 'gender' => 'M', 'father_id' => 61, 'mother_id' => 65, 'spouse_id' => '71', 'is_alive' => 1, 'biografi' => 'Cucu Bude Kusilah'],
            ['id' => 71, 'name' => 'Yatmiasih Wahyu Trisanti', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '70', 'is_alive' => 1, 'biografi' => 'Istri Febry Triawan'],
            ['id' => 72, 'name' => 'Zulfahriansyah Wahyu Putrawan', 'gender' => 'M', 'father_id' => 70, 'mother_id' => 71, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cicit Bude Kusilah'],
            ['id' => 73, 'name' => 'Shidqia Nada Alfathunisa', 'gender' => 'F', 'father_id' => 70, 'mother_id' => 71, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cicit Bude Kusilah'],
            ['id' => 74, 'name' => 'Deddy Haryono', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '62', 'is_alive' => 1, 'biografi' => 'Suami Kunwindrati'],
            ['id' => 75, 'name' => 'Yondie Dictiyanto', 'gender' => 'M', 'father_id' => 74, 'mother_id' => 62, 'spouse_id' => '76', 'is_alive' => 1, 'biografi' => 'Cucu Bude Kusilah'],
            ['id' => 76, 'name' => 'Vivi Widayanti', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '75', 'is_alive' => 1, 'biografi' => 'Istri Yondie Dictiyanto'],
            ['id' => 77, 'name' => 'Adzriel Raffa Alariiq', 'gender' => 'M', 'father_id' => 75, 'mother_id' => 76, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cicit Bude Kusilah'],
            ['id' => 78, 'name' => 'Naoura Latisha Yasmine', 'gender' => 'F', 'father_id' => 75, 'mother_id' => 76, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cicit Bude Kusilah'],
            ['id' => 79, 'name' => 'Dessy Setiadevi', 'gender' => 'F', 'father_id' => 74, 'mother_id' => 62, 'spouse_id' => '80', 'is_alive' => 1, 'biografi' => 'Cucu Bude Kusilah'],
            ['id' => 80, 'name' => 'Iwan Suswanto', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '79', 'is_alive' => 1, 'biografi' => 'Suami Dessy Setiadevi'],
            ['id' => 81, 'name' => 'Antania Citha Nabiila', 'gender' => 'F', 'father_id' => 80, 'mother_id' => 79, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cicit Bude Kusilah'],
            ['id' => 82, 'name' => 'Al Azhar Mukhtar Rabbani', 'gender' => 'M', 'father_id' => 80, 'mother_id' => 79, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cicit Bude Kusilah'],
            ['id' => 83, 'name' => 'Asep Subana', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '63', 'is_alive' => 1, 'biografi' => 'Suami Kusbardini'],
            ['id' => 84, 'name' => 'Devy Mauriza Subana', 'gender' => 'F', 'father_id' => 83, 'mother_id' => 63, 'spouse_id' => '85', 'is_alive' => 1, 'biografi' => 'Cucu Bude Kusilah'],
            ['id' => 85, 'name' => 'Kasto Yasin Efendi', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '84', 'is_alive' => 1, 'biografi' => 'Suami Devy Mauriza'],
            ['id' => 86, 'name' => 'Ashyraafin Akbar Saputra', 'gender' => 'M', 'father_id' => 85, 'mother_id' => 84, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cicit Bude Kusilah'],
            ['id' => 87, 'name' => 'Dhiyaa Anis Tsaabitah AS', 'gender' => 'F', 'father_id' => 83, 'mother_id' => 63, 'spouse_id' => '88', 'is_alive' => 1, 'biografi' => 'Cucu Bude Kusilah'],
            ['id' => 88, 'name' => 'Muhammad Naflih Ramlan', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '87', 'is_alive' => 1, 'biografi' => 'Suami Dhiyaa Anis'],
            ['id' => 89, 'name' => 'Abyan Ghazzal Abqary', 'gender' => 'M', 'father_id' => 88, 'mother_id' => 87, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cicit Bude Kusilah'],
            ['id' => 90, 'name' => 'R.Aj. Munartri Ngebnitari, A.Md', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '64', 'is_alive' => 1, 'biografi' => 'Istri Kusmahadi'],
            ['id' => 91, 'name' => 'R.M. Moch Aulia Rizqie Pratama', 'gender' => 'M', 'father_id' => 64, 'mother_id' => 90, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Kusilah'],
            ['id' => 92, 'name' => 'Mochamad Agus Prihartono (Mas Tony)', 'gender' => 'M', 'father_id' => 20, 'mother_id' => 9, 'spouse_id' => '93, 94', 'is_alive' => 1, 'biografi' => 'Anak Bude Mintarsih'],
            ['id' => 93, 'name' => 'Agustin Purnamawati', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '92', 'is_alive' => 1, 'biografi' => 'Istri ke-1 Mas Tony'],
            ['id' => 94, 'name' => 'Tuti Ediati', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '92', 'is_alive' => 1, 'biografi' => 'Istri ke-2 Mas Tony'],
            ['id' => 95, 'name' => 'Andhika Priharto', 'gender' => 'M', 'father_id' => 92, 'mother_id' => 93, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Mintarsih'],
            ['id' => 96, 'name' => 'Verani Marcelina Dwicahya', 'gender' => 'F', 'father_id' => 92, 'mother_id' => 94, 'spouse_id' => '97', 'is_alive' => 1, 'biografi' => 'Cucu Bude Mintarsih'],
            ['id' => 97, 'name' => 'Zenny Rezania Dewantary', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '96', 'is_alive' => 1, 'biografi' => 'Suami Verani Marcelina'],
            ['id' => 98, 'name' => 'Adam Adibrata Priharto', 'gender' => 'M', 'father_id' => 97, 'mother_id' => 96, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cicit Bude Mintarsih'],
            ['id' => 99, 'name' => 'Bima Nareswara Priharto', 'gender' => 'M', 'father_id' => 97, 'mother_id' => 96, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cicit Bude Mintarsih'],
            ['id' => 100, 'name' => 'Cyra Adyatma Priharto', 'gender' => 'F', 'father_id' => 97, 'mother_id' => 96, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cicit Bude Mintarsih'],
            ['id' => 101, 'name' => 'Gerry Aquinaldy Gemawan', 'gender' => 'M', 'father_id' => 92, 'mother_id' => 94, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Mintarsih'],
            ['id' => 102, 'name' => 'Nagata Zhafran Aquinaldi', 'gender' => 'M', 'father_id' => 101, 'mother_id' => null, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cicit Bude Mintarsih'],
            ['id' => 103, 'name' => 'Kaivan Zakir Aquinaldi', 'gender' => 'M', 'father_id' => 101, 'mother_id' => null, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cicit Bude Mintarsih'],
            ['id' => 104, 'name' => 'Yudi Setio Waluyo', 'gender' => 'M', 'father_id' => 20, 'mother_id' => 9, 'spouse_id' => '105', 'is_alive' => 1, 'biografi' => 'Anak Bude Mintarsih. Lahir: 1959-01-30.'],
            ['id' => 105, 'name' => 'Enny Koesrini', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '104', 'is_alive' => 1, 'biografi' => 'Istri Yudi Setio. Lahir: 1961-12-08.'],
            ['id' => 106, 'name' => 'Danang Hira Kusuma', 'gender' => 'M', 'father_id' => 104, 'mother_id' => 105, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Mintarsih. Lahir: 1991-07-11.'],
            ['id' => 107, 'name' => 'Ma Ongky', 'gender' => 'M', 'father_id' => 20, 'mother_id' => 9, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Bude Mintarsih'],
            ['id' => 108, 'name' => 'Yuli Puspitawati (Mbak Lolly)', 'gender' => 'F', 'father_id' => 20, 'mother_id' => 9, 'spouse_id' => '109', 'is_alive' => 1, 'biografi' => 'Anak Bude Mintarsih'],
            ['id' => 109, 'name' => 'Hari Witjaksono', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '108', 'is_alive' => 1, 'biografi' => 'Suami Mbak Lolly'],
            ['id' => 110, 'name' => 'Almira Anggarini Witjaksono', 'gender' => 'F', 'father_id' => 109, 'mother_id' => 108, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Mintarsih'],
            ['id' => 111, 'name' => 'Alicka Octorevia Witjaksono', 'gender' => 'F', 'father_id' => 109, 'mother_id' => 108, 'spouse_id' => '112', 'is_alive' => 1, 'biografi' => 'Cucu Bude Mintarsih'],
            ['id' => 112, 'name' => 'Pradipta Akbar Cahyono', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '111', 'is_alive' => 1, 'biografi' => 'Suami Alicka Octorevia'],
            ['id' => 113, 'name' => 'Alfarizy Bagus Kartika Witjaksono', 'gender' => 'M', 'father_id' => 109, 'mother_id' => 108, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Mintarsih'],
            ['id' => 114, 'name' => 'Aldia Ayu Prameswari Witjaksono', 'gender' => 'F', 'father_id' => 109, 'mother_id' => 108, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Mintarsih'],
            ['id' => 115, 'name' => 'Lita Kusumawardani', 'gender' => 'F', 'father_id' => 20, 'mother_id' => 9, 'spouse_id' => '116', 'is_alive' => 1, 'biografi' => 'Anak Bude Mintarsih'],
            ['id' => 116, 'name' => 'DR. Karl-Michael Reichert', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '115', 'is_alive' => 1, 'biografi' => 'Suami Lita Kusumawardani'],
            ['id' => 117, 'name' => 'Iskandi', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '10', 'is_alive' => 1, 'biografi' => 'Suami Bude Herdiyah'],
            ['id' => 118, 'name' => 'Dias Hendartono', 'gender' => 'M', 'father_id' => 117, 'mother_id' => 10, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Bude Herdiyah (Anak no 1. Belum Menikah)'],
            ['id' => 119, 'name' => 'Diah Ismari Hastuti (Mbak Mary)', 'gender' => 'F', 'father_id' => 117, 'mother_id' => 10, 'spouse_id' => '120', 'is_alive' => 1, 'biografi' => 'Anak Bude Herdiyah (Anak no 2)'],
            ['id' => 120, 'name' => 'Hendrawan bin Albert Ruslan', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '119', 'is_alive' => 1, 'biografi' => 'Suami Diah Ismari Hastuti'],
            ['id' => 121, 'name' => 'Hedi Paramita', 'gender' => 'F', 'father_id' => 120, 'mother_id' => 119, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Herdiyah'],
            ['id' => 122, 'name' => 'Henri Satria Anugrah', 'gender' => 'M', 'father_id' => 120, 'mother_id' => 119, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Herdiyah'],
            ['id' => 123, 'name' => 'Heru Iswardianto', 'gender' => 'M', 'father_id' => 117, 'mother_id' => 10, 'spouse_id' => '124, 125', 'is_alive' => 1, 'biografi' => 'Anak Bude Herdiyah (Anak no 3)'],
            ['id' => 124, 'name' => 'Rosada Yulita Sitompul', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '123', 'is_alive' => 1, 'biografi' => 'Istri 1 Heru Iswardianto'],
            ['id' => 125, 'name' => 'Betty Anggraeni binti Harsono', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '123', 'is_alive' => 1, 'biografi' => 'Istri 2 Heru Iswardianto'],
            ['id' => 126, 'name' => 'Lolita Kemuning Tyas', 'gender' => 'F', 'father_id' => 123, 'mother_id' => 124, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Herdiyah (dari Istri 1)'],
            ['id' => 127, 'name' => 'Hesa Prasetya Hadi', 'gender' => 'M', 'father_id' => 123, 'mother_id' => 124, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Herdiyah (dari Istri 1)'],
            ['id' => 128, 'name' => 'Aurelia Fibri Shofyya', 'gender' => 'F', 'father_id' => 123, 'mother_id' => 125, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Herdiyah (dari Istri 2)'],
            ['id' => 129, 'name' => 'Dian Heriadi', 'gender' => 'M', 'father_id' => 117, 'mother_id' => 10, 'spouse_id' => '130', 'is_alive' => 1, 'biografi' => 'Anak Bude Herdiyah (Anak no 4)'],
            ['id' => 130, 'name' => 'Rusliawati', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '129', 'is_alive' => 1, 'biografi' => 'Istri Dian Heriadi'],
            ['id' => 131, 'name' => 'Resinta Nazofah Heriadi', 'gender' => 'F', 'father_id' => 129, 'mother_id' => 130, 'spouse_id' => '132', 'is_alive' => 1, 'biografi' => 'Cucu Bude Herdiyah'],
            ['id' => 132, 'name' => 'Firdaus', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '131', 'is_alive' => 1, 'biografi' => 'Suami Resinta Nazofah'],
            ['id' => 133, 'name' => 'Aleefa Maryam Firnas', 'gender' => 'F', 'father_id' => 132, 'mother_id' => 131, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cicit Bude Herdiyah'],
            ['id' => 134, 'name' => 'Refani Azzroh Heriadi', 'gender' => 'F', 'father_id' => 129, 'mother_id' => 130, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Herdiyah'],
            ['id' => 135, 'name' => 'Reihan Ihsani Heriadi', 'gender' => 'M', 'father_id' => 129, 'mother_id' => 130, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Herdiyah'],
            ['id' => 136, 'name' => 'Herawan Isdianto', 'gender' => 'M', 'father_id' => 117, 'mother_id' => 10, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Bude Herdiyah (Anak no 5. Belum Menikah)'],
            ['id' => 137, 'name' => 'Nuraina (Mbak Nina)', 'gender' => 'F', 'father_id' => 117, 'mother_id' => 10, 'spouse_id' => '138', 'is_alive' => 1, 'biografi' => 'Anak Bude Herdiyah (Anak no 6)'],
            ['id' => 138, 'name' => 'Slamet Basuki bin Siswo Supadmo', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '137', 'is_alive' => 1, 'biografi' => 'Suami Nuraina'],
            ['id' => 139, 'name' => 'Nadea Feby Ayuningtyas', 'gender' => 'F', 'father_id' => 138, 'mother_id' => 137, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Herdiyah'],
            ['id' => 140, 'name' => 'Naufal Afif Zaqi', 'gender' => 'M', 'father_id' => 138, 'mother_id' => 137, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Herdiyah'],
            ['id' => 141, 'name' => 'Ismaria Handayani (Mbak Maria)', 'gender' => 'F', 'father_id' => 117, 'mother_id' => 10, 'spouse_id' => '142', 'is_alive' => 1, 'biografi' => 'Anak Bude Herdiyah (Anak no 7)'],
            ['id' => 142, 'name' => 'Tri Wahyudi Bowo Hartono', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '141', 'is_alive' => 1, 'biografi' => 'Suami Ismaria Handayani'],
            ['id' => 143, 'name' => 'Oriza Sativa Salsabila', 'gender' => 'F', 'father_id' => 142, 'mother_id' => 141, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Herdiyah'],
            ['id' => 144, 'name' => 'Ovia Syifa Salsabila', 'gender' => 'F', 'father_id' => 142, 'mother_id' => 141, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Herdiyah'],
            ['id' => 145, 'name' => 'Ismed Hendargo', 'gender' => 'M', 'father_id' => 117, 'mother_id' => 10, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Bude Herdiyah (Anak no 8. Belum Menikah)'],
            ['id' => 146, 'name' => 'Didit Wiriawan', 'gender' => 'M', 'father_id' => 12, 'mother_id' => 21, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Pakde Ilyas'],
            ['id' => 147, 'name' => 'Gatot Himawan', 'gender' => 'M', 'father_id' => 12, 'mother_id' => 21, 'spouse_id' => '148', 'is_alive' => 1, 'biografi' => 'Anak Pakde Ilyas'],
            ['id' => 148, 'name' => 'Mei Estiningsih', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '147', 'is_alive' => 1, 'biografi' => 'Istri Gatot Himawan'],
            ['id' => 149, 'name' => 'Mochamad Gentur Pradipta', 'gender' => 'M', 'father_id' => 147, 'mother_id' => 148, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Ilyas'],
            ['id' => 150, 'name' => 'Mochamad Syahda Mahardika', 'gender' => 'M', 'father_id' => 147, 'mother_id' => 148, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Ilyas'],
            ['id' => 151, 'name' => 'Mochamad Zidan Rafif', 'gender' => 'M', 'father_id' => 147, 'mother_id' => 148, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Ilyas'],
            ['id' => 152, 'name' => 'Mochamad Naufal Ardiona', 'gender' => 'M', 'father_id' => 147, 'mother_id' => 148, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Ilyas'],
            ['id' => 153, 'name' => 'Bowo Setiawan', 'gender' => 'M', 'father_id' => 12, 'mother_id' => 21, 'spouse_id' => '154', 'is_alive' => 1, 'biografi' => 'Anak Pakde Ilyas'],
            ['id' => 154, 'name' => 'Irma Khusnawati', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '153', 'is_alive' => 1, 'biografi' => 'Istri Bowo Setiawan'],
            ['id' => 155, 'name' => 'Khanza Safiya Rhumaisa', 'gender' => 'F', 'father_id' => 153, 'mother_id' => 154, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Ilyas'],
            ['id' => 156, 'name' => 'Nuha Qonita Rhumaisa', 'gender' => 'F', 'father_id' => 153, 'mother_id' => 154, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Ilyas'],
            ['id' => 157, 'name' => 'Rasmi Nindita', 'gender' => 'F', 'father_id' => 12, 'mother_id' => 21, 'spouse_id' => '158', 'is_alive' => 1, 'biografi' => 'Anak Pakde Ilyas'],
            ['id' => 158, 'name' => 'Adi Endharto', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '157', 'is_alive' => 1, 'biografi' => 'Suami Rasmi Nindita'],
            ['id' => 159, 'name' => 'Ully Ardimijayanti', 'gender' => 'F', 'father_id' => 13, 'mother_id' => 22, 'spouse_id' => '160', 'is_alive' => 1, 'biografi' => 'Anak Pakde Muhadi'],
            ['id' => 160, 'name' => 'Duan Agustina', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '159', 'is_alive' => 1, 'biografi' => 'Suami Ully Ardimijayanti'],
            ['id' => 161, 'name' => 'Artvanya Zahra Khalisa Adjani (Vanya)', 'gender' => 'F', 'father_id' => 160, 'mother_id' => 159, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Muhadi'],
            ['id' => 162, 'name' => 'Nirina Zahra Laila Ramadhani', 'gender' => 'F', 'father_id' => 160, 'mother_id' => 159, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Muhadi'],
            ['id' => 163, 'name' => 'Jetty Ardimijayani', 'gender' => 'F', 'father_id' => 13, 'mother_id' => 22, 'spouse_id' => '164', 'is_alive' => 1, 'biografi' => 'Anak Pakde Muhadi'],
            ['id' => 164, 'name' => 'Tatang Surya Laksmana', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '163', 'is_alive' => 1, 'biografi' => 'Suami Jetty Ardimijayani'],
            ['id' => 165, 'name' => 'Putri Ramaniya Ardilaksmana (Raniya)', 'gender' => 'F', 'father_id' => 164, 'mother_id' => 163, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Muhadi'],
            ['id' => 166, 'name' => 'Ramananda Prasetya Ardilaksmana (Ramanda)', 'gender' => 'M', 'father_id' => 164, 'mother_id' => 163, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Muhadi'],
            ['id' => 167, 'name' => 'Fifi Ardiaugustina', 'gender' => 'F', 'father_id' => 13, 'mother_id' => 22, 'spouse_id' => '168', 'is_alive' => 1, 'biografi' => 'Anak Pakde Muhadi'],
            ['id' => 168, 'name' => 'Tri Adi Sentosa', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '167', 'is_alive' => 1, 'biografi' => 'Suami Fifi Ardiaugustina'],
            ['id' => 169, 'name' => 'Salma Shafa Humaira', 'gender' => 'F', 'father_id' => 168, 'mother_id' => 167, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Muhadi'],
            ['id' => 170, 'name' => 'Abid Muhammad Faiz', 'gender' => 'M', 'father_id' => 168, 'mother_id' => 167, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Muhadi'],
            ['id' => 171, 'name' => 'Ihsan Ibrahim AlMasyriqi (Bram)', 'gender' => 'M', 'father_id' => 168, 'mother_id' => 167, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Muhadi'],
            ['id' => 172, 'name' => 'Hashin Muhibburahman', 'gender' => 'M', 'father_id' => 168, 'mother_id' => 167, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Muhadi'],
            ['id' => 173, 'name' => 'Putri Ardiliscahyani', 'gender' => 'F', 'father_id' => 13, 'mother_id' => 22, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Pakde Muhadi'],
            ['id' => 174, 'name' => 'Rury Arum Jati', 'gender' => 'F', 'father_id' => 14, 'mother_id' => 23, 'spouse_id' => '175', 'is_alive' => 1, 'biografi' => 'Anak Pakde Hardono'],
            ['id' => 175, 'name' => 'Ali Prasetya', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '174', 'is_alive' => 1, 'biografi' => 'Suami Rury Arum Jati'],
            ['id' => 176, 'name' => 'Pranadja Albirru Rakabumi', 'gender' => 'M', 'father_id' => 175, 'mother_id' => 174, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Hardono'],
            ['id' => 177, 'name' => 'Yona Reviana', 'gender' => 'F', 'father_id' => 14, 'mother_id' => 23, 'spouse_id' => '178', 'is_alive' => 1, 'biografi' => 'Anak Pakde Hardono'],
            ['id' => 178, 'name' => 'Triawan Aryo Desanto', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '177', 'is_alive' => 1, 'biografi' => 'Suami Yona Reviana'],
            ['id' => 179, 'name' => 'Thalita Azkadina Xaviana', 'gender' => 'F', 'father_id' => 178, 'mother_id' => 177, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Hardono'],
            ['id' => 180, 'name' => 'Ayu Nila Sari', 'gender' => 'F', 'father_id' => 14, 'mother_id' => 23, 'spouse_id' => '181', 'is_alive' => 1, 'biografi' => 'Anak Pakde Hardono'],
            ['id' => 181, 'name' => 'Iji Sangaji', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '180', 'is_alive' => 1, 'biografi' => 'Suami Ayu Nila Sari'],
            ['id' => 182, 'name' => 'Alzena Calya Parahita', 'gender' => 'F', 'father_id' => 181, 'mother_id' => 180, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Hardono'],
            ['id' => 183, 'name' => 'Alicka Khayyara Pradeepta', 'gender' => 'F', 'father_id' => 181, 'mother_id' => 180, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Hardono'],
            ['id' => 184, 'name' => 'Teriani Anggi', 'gender' => 'F', 'father_id' => 14, 'mother_id' => 23, 'spouse_id' => '185', 'is_alive' => 1, 'biografi' => 'Anak Pakde Hardono'],
            ['id' => 185, 'name' => 'Rahmat Indrani', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '184', 'is_alive' => 1, 'biografi' => 'Suami Teriani Anggi'],
            ['id' => 186, 'name' => 'Djura Ahmad Hamzah', 'gender' => 'M', 'father_id' => 185, 'mother_id' => 184, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Hardono'],
            ['id' => 187, 'name' => 'Maya Anggraini', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '15', 'is_alive' => 1, 'biografi' => 'Istri Pakde Nursaid'],
            ['id' => 188, 'name' => 'Nuning Setiawati', 'gender' => 'F', 'father_id' => 15, 'mother_id' => 187, 'spouse_id' => '189', 'is_alive' => 1, 'biografi' => 'Anak Pakde Nursaid'],
            ['id' => 189, 'name' => 'Robby Kurniawan', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '188', 'is_alive' => 1, 'biografi' => 'Suami Nuning Setiawati'],
            ['id' => 190, 'name' => 'Odli Aulia', 'gender' => 'M', 'father_id' => 189, 'mother_id' => 188, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Nursaid'],
            ['id' => 191, 'name' => 'Cut Rehana Putri', 'gender' => 'F', 'father_id' => 189, 'mother_id' => 188, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Nursaid'],
            ['id' => 192, 'name' => 'Tintus Priambodho', 'gender' => 'M', 'father_id' => 15, 'mother_id' => 187, 'spouse_id' => '193', 'is_alive' => 1, 'biografi' => 'Anak Pakde Nursaid'],
            ['id' => 193, 'name' => 'Eva Sulastri', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '192', 'is_alive' => 1, 'biografi' => 'Istri Tintus Priambodho'],
            ['id' => 194, 'name' => 'Hanania Testa Anggraini', 'gender' => 'F', 'father_id' => 192, 'mother_id' => 193, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Nursaid'],
            ['id' => 195, 'name' => 'Dini Agustin', 'gender' => 'F', 'father_id' => 192, 'mother_id' => 193, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Nursaid'],
            ['id' => 196, 'name' => 'Muhammad Halim Priambodho', 'gender' => 'M', 'father_id' => 192, 'mother_id' => 193, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Nursaid'],
            ['id' => 197, 'name' => 'Ade Novian Trilaksono', 'gender' => 'M', 'father_id' => 15, 'mother_id' => 187, 'spouse_id' => '198', 'is_alive' => 1, 'biografi' => 'Anak Pakde Nursaid'],
            ['id' => 198, 'name' => 'Baroro Astiani', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '197', 'is_alive' => 1, 'biografi' => 'Mantan Istri Ade Novian'],
            ['id' => 199, 'name' => 'Al Fahri Adiyalaksono', 'gender' => 'M', 'father_id' => 197, 'mother_id' => 198, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Nursaid'],
            ['id' => 200, 'name' => 'Adisti Madinah Adiyalaksono', 'gender' => 'F', 'father_id' => 197, 'mother_id' => 198, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Nursaid'],
            ['id' => 201, 'name' => 'Adinda Al Safa Adiyalaksono', 'gender' => 'F', 'father_id' => 197, 'mother_id' => 198, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Nursaid'],
            ['id' => 202, 'name' => 'Altaf Adiyalaksono', 'gender' => 'M', 'father_id' => 197, 'mother_id' => 198, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Nursaid'],
            ['id' => 203, 'name' => 'Esti Agustiarini', 'gender' => 'F', 'father_id' => 15, 'mother_id' => 187, 'spouse_id' => '204', 'is_alive' => 1, 'biografi' => 'Anak Pakde Nursaid'],
            ['id' => 204, 'name' => 'Teuku Hasan Azhari', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '203', 'is_alive' => 1, 'biografi' => 'Suami Esti Agustiarini'],
            ['id' => 205, 'name' => 'Cut Nabila', 'gender' => 'F', 'father_id' => 204, 'mother_id' => 203, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Nursaid'],
            ['id' => 206, 'name' => 'Teuku Afan Abdullah Azhari', 'gender' => 'M', 'father_id' => 204, 'mother_id' => 203, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Nursaid'],
            ['id' => 207, 'name' => 'Cut Salimah', 'gender' => 'F', 'father_id' => 204, 'mother_id' => 203, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Nursaid'],
            ['id' => 208, 'name' => 'Umar Azhari', 'gender' => 'M', 'father_id' => 204, 'mother_id' => 203, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Nursaid'],
            ['id' => 209, 'name' => 'Afif Rizki Kurniawan', 'gender' => 'M', 'father_id' => 15, 'mother_id' => 187, 'spouse_id' => '210', 'is_alive' => 1, 'biografi' => 'Anak Pakde Nursaid'],
            ['id' => 210, 'name' => 'Anggun Vika Aryani', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '209', 'is_alive' => 1, 'biografi' => 'Istri Afif Rizki'],
            ['id' => 211, 'name' => 'Oktasya Aileen Vizki Tafisha', 'gender' => 'F', 'father_id' => 209, 'mother_id' => 210, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Pakde Nursaid'],
            ['id' => 212, 'name' => 'Fanny Eka Praditya', 'gender' => 'M', 'father_id' => 16, 'mother_id' => 24, 'spouse_id' => '213', 'is_alive' => 1, 'biografi' => 'Anak Papah Hoho'],
            ['id' => 213, 'name' => 'Novilia', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '212', 'is_alive' => 1, 'biografi' => 'Istri Fanny Eka Praditya'],
            ['id' => 214, 'name' => 'Ega', 'gender' => 'M', 'father_id' => 212, 'mother_id' => 213, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Papah Hoho'],
            ['id' => 215, 'name' => 'Ibea', 'gender' => 'F', 'father_id' => 212, 'mother_id' => 213, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Papah Hoho'],
            ['id' => 216, 'name' => 'Rubby Missilia Dwiaryanti', 'gender' => 'F', 'father_id' => 16, 'mother_id' => 24, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Papah Hoho'],
            ['id' => 217, 'name' => 'Hernita Kusuma Wardani', 'gender' => 'F', 'father_id' => 25, 'mother_id' => 17, 'spouse_id' => '218', 'is_alive' => 1, 'biografi' => 'Anak Bude Murniati'],
            ['id' => 218, 'name' => 'Dhika Rahardian', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '217', 'is_alive' => 1, 'biografi' => 'Suami Hernita'],
            ['id' => 219, 'name' => 'Muhammad Davin Rahardian', 'gender' => 'M', 'father_id' => 218, 'mother_id' => 217, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Murniati'],
            ['id' => 220, 'name' => 'Navisha Daneen Rahardian', 'gender' => 'F', 'father_id' => 218, 'mother_id' => 217, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Bude Murniati'],
            ['id' => 221, 'name' => 'Mira Sari Valentina', 'gender' => 'F', 'father_id' => 25, 'mother_id' => 17, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Bude Murniati'],
            ['id' => 222, 'name' => 'Ibu Purwokerto', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '5', 'is_alive' => 0, 'biografi' => 'Istri 1 Mas Kahirman'],
            ['id' => 223, 'name' => 'Mbak Tutik', 'gender' => 'F', 'father_id' => 5, 'mother_id' => 222, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Mas Kahirman'],
            ['id' => 224, 'name' => 'Mas Gatot', 'gender' => 'M', 'father_id' => 5, 'mother_id' => 222, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Mas Kahirman'],
            ['id' => 225, 'name' => 'Ibu Sudinah', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '5', 'is_alive' => 0, 'biografi' => 'Istri 2 Mas Kahirman'],
            ['id' => 226, 'name' => 'Suskandar', 'gender' => 'M', 'father_id' => 5, 'mother_id' => 225, 'spouse_id' => null, 'is_alive' => 0, 'biografi' => 'Anak Mas Kahirman (Meninggal umur 1 tahun)'],
            ['id' => 227, 'name' => 'Bambang Irawan', 'gender' => 'M', 'father_id' => 5, 'mother_id' => 225, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Mas Kahirman'],
            ['id' => 228, 'name' => 'Endang Sulistya Ningsih', 'gender' => 'F', 'father_id' => 5, 'mother_id' => 225, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Mas Kahirman'],
            ['id' => 229, 'name' => 'Ninik Irianti Ningsih', 'gender' => 'F', 'father_id' => 5, 'mother_id' => 225, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Mas Kahirman'],
            ['id' => 230, 'name' => 'Yuli Yanti Ningsih', 'gender' => 'F', 'father_id' => 5, 'mother_id' => 225, 'spouse_id' => null, 'is_alive' => 0, 'biografi' => 'Anak Mas Kahirman (Meninggal)'],
            ['id' => 231, 'name' => 'Titik Marti Ningsih', 'gender' => 'F', 'father_id' => 5, 'mother_id' => 225, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Mas Kahirman'],
            ['id' => 232, 'name' => 'Agus Slamet Jumadi (Doto)', 'gender' => 'M', 'father_id' => 5, 'mother_id' => 225, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Mas Kahirman'],
            ['id' => 233, 'name' => 'Ibu Nikah Siri Solo', 'gender' => 'F', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '5', 'is_alive' => 1, 'biografi' => 'Istri 3 Mas Kahirman (Nikah 2013)'],
            ['id' => 234, 'name' => 'Budi', 'gender' => 'M', 'father_id' => 5, 'mother_id' => 233, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Mas Kahirman'],
            ['id' => 235, 'name' => 'Sri Moempoeni (Mbak Menik)', 'gender' => 'F', 'father_id' => 18, 'mother_id' => 6, 'spouse_id' => '236', 'is_alive' => 1, 'biografi' => 'Anak Bude Murtiwi'],
            ['id' => 236, 'name' => 'Freddy Afrianto', 'gender' => 'M', 'father_id' => null, 'mother_id' => null, 'spouse_id' => '235', 'is_alive' => 1, 'biografi' => 'Suami Mbak Menik'],
            ['id' => 237, 'name' => 'Fitri Paramietha', 'gender' => 'F', 'father_id' => 236, 'mother_id' => 235, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Mbak Menik'],
            ['id' => 238, 'name' => 'Ridho Pandu Afrianto', 'gender' => 'M', 'father_id' => 236, 'mother_id' => 235, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Anak Mbak Menik'],
            ['id' => 239, 'name' => 'Ahnaf Rizki Mufrianto', 'gender' => 'M', 'father_id' => null, 'mother_id' => 237, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Mbak Menik'],
            ['id' => 240, 'name' => 'Anindya Jihan Rizki', 'gender' => 'F', 'father_id' => null, 'mother_id' => 237, 'spouse_id' => null, 'is_alive' => 1, 'biografi' => 'Cucu Mbak Menik'],
        ];

        foreach ($data as $item) {
            DB::table('family_members')->insert([
                'id' => $item['id'],
                'name' => $item['name'],
                'gender' => $item['gender'],
                'father_id' => $item['father_id'],
                'mother_id' => $item['mother_id'],
                'spouse_id' => $item['spouse_id'],
                'is_alive' => $item['is_alive'],
                'biografi' => $item['biografi'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}